// License crypto - generate and validate activation codes
// Uses HMAC-SHA256 to ensure codes can only be generated by the admin
// 
// Code format: XXXX-XXXX-XXXX-XXXX-XXXX (20 chars)
//   [machine_id: 8 hex] [expiry: 6 digits YYMMDD] [duration: 2 chars] [signature: 4 hex]
//
// Example: A5C6-9B04-260506-30-DB9A
//   Machine: A5C69B04  Expiry: 06/05/2026  Duration: 30 (30 days)  Sig: DB9A

import crypto from 'crypto';

// Secret key - only the admin knows this
const SECRET_KEY = 'PM-2025-LICENSE-ACTIVATION-KEY';

// Duration codes are exactly 2 chars for the code format
export type LicenseDuration = '30' | '90' | '18' | '36' | 'UL';

export const DURATION_OPTIONS: { value: LicenseDuration; label: string; days: number }[] = [
  { value: '30', label: '30 jours', days: 30 },
  { value: '90', label: '3 mois', days: 90 },
  { value: '18', label: '6 mois', days: 180 },
  { value: '36', label: '1 an', days: 365 },
  { value: 'UL', label: 'Illimité', days: 36500 },
];

function getDurationCode(duration: LicenseDuration): string {
  return duration;
}

function getDurationDays(code: string): number {
  const opt = DURATION_OPTIONS.find(d => d.value === code);
  return opt ? opt.days : 30;
}

function getDurationLabel(code: string): string {
  const opt = DURATION_OPTIONS.find(d => d.value === code);
  return opt ? opt.label : '30 jours';
}

/**
 * Generate an activation code
 */
export function generateActivationCode(machineCode: string, duration: LicenseDuration): {
  code: string;
  expiryDate: string;
  durationLabel: string;
} {
  // Normalize machine code
  const machineId = machineCode.replace(/-/g, '').toUpperCase().substring(0, 8);

  // Calculate expiry date
  const days = getDurationDays(duration);
  const expiry = new Date();
  expiry.setDate(expiry.getDate() + days);
  const expiryDate = duration === 'UL' ? '2099-12-31' : expiry.toISOString().split('T')[0];

  // Format expiry as YYMMDD
  const yy = expiryDate.substring(2, 4);
  const mm = expiryDate.substring(5, 7);
  const dd = expiryDate.substring(8, 10);
  const expiryShort = `${yy}${mm}${dd}`;

  // Duration code (2 chars)
  const durCode = getDurationCode(duration);

  // HMAC signature of machine_id + expiry + duration
  const payload = `${machineId}${expiryShort}${durCode}`;
  const sig = crypto
    .createHmac('sha256', SECRET_KEY)
    .update(payload)
    .digest('hex')
    .substring(0, 4)
    .toUpperCase();

  // Build code: machine(8) + expiry(6) + dur(2) + sig(4) = 20 chars
  const raw = `${machineId}${expiryShort}${durCode}${sig}`;
  const code = `${raw.slice(0, 4)}-${raw.slice(4, 8)}-${raw.slice(8, 12)}-${raw.slice(12, 16)}-${raw.slice(16, 20)}`;

  return {
    code,
    expiryDate,
    durationLabel: getDurationLabel(durCode),
  };
}

/**
 * Validate an activation code for a given machine
 */
export function validateActivationCode(code: string, machineHash: string): {
  valid: boolean;
  expiryDate?: string;
  durationCode?: string;
  durationLabel?: string;
  error?: string;
} {
  try {
    // Normalize
    const raw = code.replace(/-/g, '').toUpperCase();
    
    if (raw.length !== 20) {
      return { valid: false, error: 'Format de code invalide' };
    }

    // Parse parts
    const machineId = raw.slice(0, 8);       // Machine ID (8 hex)
    const expiryShort = raw.slice(8, 14);    // YYMMDD (6 digits)
    const durCode = raw.slice(14, 16);       // Duration code (2 chars)
    const sig = raw.slice(16, 20);           // HMAC signature (4 hex)

    // Verify machine ID matches
    const currentMachineId = machineHash.substring(0, 8).toUpperCase();
    if (machineId !== currentMachineId) {
      return { valid: false, error: 'Ce code ne correspond pas à cette machine' };
    }

    // Verify duration code is valid
    if (!DURATION_OPTIONS.find(d => d.value === durCode)) {
      return { valid: false, error: 'Code invalide' };
    }

    // Verify HMAC signature
    const payload = `${machineId}${expiryShort}${durCode}`;
    const expectedSig = crypto
      .createHmac('sha256', SECRET_KEY)
      .update(payload)
      .digest('hex')
      .substring(0, 4)
      .toUpperCase();

    if (sig !== expectedSig) {
      return { valid: false, error: 'Code invalide (signature incorrecte)' };
    }

    // Reconstruct expiry date
    const year = `20${expiryShort.slice(0, 2)}`;
    const month = expiryShort.slice(2, 4);
    const day = expiryShort.slice(4, 6);
    const expiryDate = `${year}-${month}-${day}`;

    const expDate = new Date(expiryDate);
    if (isNaN(expDate.getTime())) {
      return { valid: false, error: 'Code invalide (date incorrecte)' };
    }

    // Check if expired
    if (expiryDate !== '2099-12-31') {
      const now = new Date();
      now.setHours(23, 59, 59, 999);
      if (expDate < now) {
        return { valid: false, error: 'Ce code a expiré' };
      }
    }

    return {
      valid: true,
      expiryDate,
      durationCode: durCode,
      durationLabel: getDurationLabel(durCode),
    };
  } catch (e) {
    return { valid: false, error: 'Code invalide' };
  }
}
